services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: log2db
      POSTGRES_USER: log2pg
      POSTGRES_PASSWORD: log2pg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://log2pg:log2pg@db/log2db

volumes:
  postgres_data: